# Generated by Django 5.1.6 on 2025-03-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_populate_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
    ]
